spring:
  application:
    name: notice
  cache:
    type: simple
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
    org.hibernate.orm.jdbc.bind: TRACE

file:
  path: ./uploads/

server:
  port: 8080
